"""Added binding_id column to the student table

Revision ID: 022056afb0f4
Revises: 7712884e7ed9
Create Date: 2025-10-05 13:38:05.808086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022056afb0f4'
down_revision = '7712884e7ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('binding_id', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('binding_id')

    # ### end Alembic commands ###
