"""Added ondelete cascade in the attendance records for the student id column

Revision ID: 0f0c508935c5
Revises: 66a77a97416f
Create Date: 2025-10-12 11:11:12.163525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0c508935c5'
down_revision = '66a77a97416f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_record_student_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_record_student_id_fkey'), 'student', ['student_id'], ['id'])

    # ### end Alembic commands ###
