"""Added unique constraint to device binding id int the student table

Revision ID: 1eb62475491c
Revises: a28ff108e83b
Create Date: 2025-10-10 10:54:26.993912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb62475491c'
down_revision = 'a28ff108e83b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_binding_id'))
        batch_op.create_index(batch_op.f('ix_student_binding_id'), ['binding_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_binding_id'))
        batch_op.create_index(batch_op.f('ix_student_binding_id'), ['binding_id'], unique=False)

    # ### end Alembic commands ###
