"""Added venue column to the defaultSchedule Table

Revision ID: 32cac19d9a07
Revises: 58dec9e0406b
Create Date: 2025-10-02 07:58:51.614227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32cac19d9a07'
down_revision = '58dec9e0406b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('default_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue', sa.String(length=25), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('default_schedule', schema=None) as batch_op:
        batch_op.drop_column('venue')

    # ### end Alembic commands ###
