"""Full AMS Schema

Revision ID: 36d473c810b0
Revises: b740cca77faa
Create Date: 2025-09-29 13:50:58.397026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d473c810b0'
down_revision = 'b740cca77faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('student',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('subject',
    sa.Column('subject_code', sa.String(length=10), nullable=False),
    sa.Column('subject_mnemonic', sa.String(length=100), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('subject_code')
    )
    op.create_table('cr',
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('faculty_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.String(length=20), nullable=False),
    sa.Column('subject_code', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['subject.subject_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('default_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('timing', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['faculty_assignment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('timing', sa.Time(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['faculty_assignment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_record')
    op.drop_table('schedule')
    op.drop_table('default_schedule')
    op.drop_table('faculty_assignment')
    op.drop_table('cr')
    op.drop_table('subject')
    op.drop_table('student')
    op.drop_table('faculty')
    # ### end Alembic commands ###
