"""Add composite indices for performance optimization and table names

Revision ID: 40948c67326c
Revises: 0f0c508935c5
Create Date: 2025-10-12 16:00:19.968288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40948c67326c'
down_revision = '0f0c508935c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_session_student', ['session_id', 'student_id'], unique=False)

    with op.batch_alter_table('default_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_default_schedule_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_default_schedule_day_of_week'), ['day_of_week'], unique=False)

    with op.batch_alter_table('faculty_assignment', schema=None) as batch_op:
        batch_op.create_index('idx_assignment_class', ['year', 'department', 'section'], unique=False)
        batch_op.create_index('idx_assignment_lookup', ['faculty_id', 'subject_code', 'year', 'department', 'section'], unique=False)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index('idx_schedule_date_assignment', ['date', 'assignment_id'], unique=False)
        batch_op.create_index('idx_schedule_date_status', ['date', 'status'], unique=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index('idx_student_class', ['year', 'department', 'section'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index('idx_student_class')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index('idx_schedule_date_status')
        batch_op.drop_index('idx_schedule_date_assignment')

    with op.batch_alter_table('faculty_assignment', schema=None) as batch_op:
        batch_op.drop_index('idx_assignment_lookup')
        batch_op.drop_index('idx_assignment_class')

    with op.batch_alter_table('default_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_default_schedule_day_of_week'))
        batch_op.drop_index(batch_op.f('ix_default_schedule_assignment_id'))

    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.drop_index('idx_attendance_session_student')

    # ### end Alembic commands ###
