"""Added indexing to several columns to improve the speed of query

Revision ID: 4a20c4b18053
Revises: 1eb62475491c
Create Date: 2025-10-11 14:22:46.371467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a20c4b18053'
down_revision = '1eb62475491c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculty_assignment_faculty_id'), ['faculty_id'], unique=False)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_status'))
        batch_op.drop_index(batch_op.f('ix_schedule_date'))

    with op.batch_alter_table('faculty_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_assignment_faculty_id'))

    # ### end Alembic commands ###
