"""Add FCM tokens and notification logs tables

Revision ID: 5cd92b6c04c2
Revises: af94982183e8
Create Date: 2025-10-07 14:14:48.167505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd92b6c04c2'
down_revision = 'af94982183e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fcm_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_email', sa.String(length=255), nullable=False),
    sa.Column('fcm_token', sa.Text(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_email', 'device_type', name='unique_email_device')
    )
    with op.batch_alter_table('fcm_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fcm_tokens_student_email'), ['student_email'], unique=False)

    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_email', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_cr_email'), ['cr_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_cr_email'))

    op.drop_table('notification_logs')
    with op.batch_alter_table('fcm_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fcm_tokens_student_email'))

    op.drop_table('fcm_tokens')
    # ### end Alembic commands ###
