"""Added roll_number column to Student Table

Revision ID: 5f968d46c69f
Revises: 40948c67326c
Create Date: 2025-12-13 21:55:52.739188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f968d46c69f'
down_revision = '40948c67326c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roll_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('roll_number')

    # ### end Alembic commands ###
