"""Added ondelete cascade in the attendance records for the session id column

Revision ID: 66a77a97416f
Revises: 4a20c4b18053
Create Date: 2025-10-12 11:07:54.238534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a77a97416f'
down_revision = '4a20c4b18053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_record_session_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'schedule', ['session_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_record_session_id_fkey'), 'schedule', ['session_id'], ['id'])

    # ### end Alembic commands ###
