"""Add venue to schedule table

Revision ID: 885404298c67
Revises: 36d473c810b0
Create Date: 2025-09-29 14:31:26.900578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885404298c67'
down_revision = '36d473c810b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculty_assignment_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_assignment_section'), ['section'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_assignment_year'), ['year'], unique=False)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue', sa.String(length=50), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_section'), ['section'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_year'))
        batch_op.drop_index(batch_op.f('ix_student_section'))
        batch_op.drop_index(batch_op.f('ix_student_department'))

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('venue')

    with op.batch_alter_table('faculty_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_assignment_year'))
        batch_op.drop_index(batch_op.f('ix_faculty_assignment_section'))
        batch_op.drop_index(batch_op.f('ix_faculty_assignment_department'))

    # ### end Alembic commands ###
