"""Add otp column to schedule table

Revision ID: 936fef563069
Revises: 32cac19d9a07
Create Date: 2025-10-03 17:07:39.178649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936fef563069'
down_revision = '32cac19d9a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('otp')

    # ### end Alembic commands ###
