"""Added indexing on the student table binding_id column

Revision ID: a28ff108e83b
Revises: b66f62e9bc24
Create Date: 2025-10-09 10:41:44.973892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28ff108e83b'
down_revision = 'b66f62e9bc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_binding_id'), ['binding_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_binding_id'))

    # ### end Alembic commands ###
