"""Enabled indexing in FacultyAssignment table subject_code and Schedule table assignment_idd columns

Revision ID: af94982183e8
Revises: fbc2fbbc7ca3
Create Date: 2025-10-06 18:30:57.493101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af94982183e8'
down_revision = 'fbc2fbbc7ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculty_assignment_subject_code'), ['subject_code'], unique=False)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_assignment_id'), ['assignment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_assignment_id'))

    with op.batch_alter_table('faculty_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_assignment_subject_code'))

    # ### end Alembic commands ###
