"""Add otp_created_at column to schedule table

Revision ID: b66f62e9bc24
Revises: 5cd92b6c04c2
Create Date: 2025-10-08 00:33:04.692574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b66f62e9bc24'
down_revision = '5cd92b6c04c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('otp_created_at')

    # ### end Alembic commands ###
