"""Add mobile column to cr table

Revision ID: c84b852ff004
Revises: 885404298c67
Create Date: 2025-09-29 19:30:17.386058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84b852ff004'
down_revision = '885404298c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cr', schema=None) as batch_op:
        batch_op.drop_column('mobile')

    # ### end Alembic commands ###
