"""Added ON DELETE CASCADE to CR-Student relationship

Revision ID: f732a58dfccd
Revises: ca1808576c26
Create Date: 2025-10-01 20:58:26.637079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f732a58dfccd'
down_revision = 'ca1808576c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cr', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cr_student_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('default_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('default_schedule_assignment_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'faculty_assignment', ['assignment_id'], ['id'])

    with op.batch_alter_table('faculty_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('faculty_assignment_subject_code_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'subject', ['subject_code'], ['subject_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('faculty_assignment_subject_code_fkey'), 'subject', ['subject_code'], ['subject_code'], ondelete='CASCADE')

    with op.batch_alter_table('default_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('default_schedule_assignment_id_fkey'), 'faculty_assignment', ['assignment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cr', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cr_student_id_fkey'), 'student', ['student_id'], ['id'])

    # ### end Alembic commands ###
