"""Enabled indexing in AttendanceRecord table student_id and session_id columns

Revision ID: fbc2fbbc7ca3
Revises: 022056afb0f4
Create Date: 2025-10-06 18:26:41.151696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc2fbbc7ca3'
down_revision = '022056afb0f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_record_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_record_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_record_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_record_session_id'))

    # ### end Alembic commands ###
